MoviesDjango/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
     #url(r'^$', 'moviesApp.views.index', name='index'),
    url(r'^moviesApp/', include('moviesApp.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

moviesApp/urls.py
from django.conf.urls import patterns, include, url
import moviesApp.views

urlpatterns = patterns('',
    # Examples:
     url(r'^movielist/$', moviesApp.views.ListContactView.as_view()),
     url(r'^moviechar/(?P<moviename>\w+)/$', moviesApp.views.ListCharView.as_view()), #moviename passed as a param
     #url(r'^moviechar/(?P<moviename>\w+)/$', 'moviesApp.views.moviechar'),
     url(r'^actorlist/$', moviesApp.views.ListActorView.as_view()),
     url(r'^actorcreate/$', moviesApp.views.CreateActorView.as_view()),
     url(r'^moviecreate/$', moviesApp.views.CreateMovieView.as_view()),
     url(r'^actorcreate/success/$', 'moviesApp.views.success'),
     url(r'^moviecreate/success/$', 'moviesApp.views.success'),
)

moviesApp/models.py
from django.db import models
    
    
class Person(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    dob = models.CharField(max_length=50)
    
    #Inherit Actor and Director from Person class
class Actor(Person):
    awards = models.CharField(max_length=200) #Awards as an Actor
    total_credits = models.IntegerField(default=0) #Total Credits as an Actor
    
    # An actor could also be a director , so we separate these entities
class Director(Person):
    awards = models.CharField(max_length=200) #Awards as a Director
    total_credits = models.IntegerField(default=0) #Total Credits as a Director
    
    
class Movie(models.Model):
    title = models.CharField(max_length=100)
    rel_date = models.CharField(max_length=50)
    imdb_score = models.FloatField(max_length=2)
    genre = models.CharField(max_length=100)
    actor = models.ManyToManyField(Actor)
    director = models.ForeignKey(Director)

class Role(models.Model):
    character = models.CharField(max_length=100)
    movie = models.ForeignKey(Movie)
    actor = models.ForeignKey(Actor)

#p = Person(name='Quentin Tarantino', dob='March 27, 1963')
#p.save()

#p = Person.objects.get(name__iexact="quentin tarantino")
#d = Director(person_ptr_id=pid, awards='Nominated for 3 oscars', total_credits=10)
#d.save()
#d = Director(person_ptr_id=p.id, awards='Won 2 oscars', total_credits=17)
#d.save()
#p.save()

moviesApp/views.py
from django.shortcuts import render,render_to_response
from moviesApp.models import Actor,Director,Person,Movie,Role
from django.http import HttpResponse, HttpResponseNotFound
from django.views.generic import ListView,View,CreateView
from django.forms import CheckboxSelectMultiple,SelectMultiple,ModelForm
# Create your views here.



class ListContactView(ListView):

    model = Movie
    template_name = 'movie_l.html'
    


class ListCharView(View):

    def get(self, request,moviename): #moviename is mentioned as a param in the function not class!
        m = Movie.objects.get(title__iexact=moviename)
        #print(m.title)
        r = Role.objects.filter(movie=m.id)
        print(r)
        return render_to_response('moviechar_list.html',{'queryset':r, 'movie':m.title}) #Awesome Way to pass multiple params to template
        
 
class ListActorView(ListView):

    model = Actor
    template_name = 'actor_list.html'
    
            
            
class CreateActorView(CreateView):
    model = Actor
    template_name = 'actor_create.html'
    success_url = 'success'
    
    


class MoviesCreateForm(ModelForm):
    class Meta:
        model = Movie
        fields = ('title', 'genre', 'actor')
        b = [y.name for y in Actor.objects.all()]
        widgets = {
            #'actor': SelectMultiple(attrs=b)
            'actor': CheckboxSelectMultiple()
        }
   
    
class CreateMovieView(CreateView):
    model = Movie
    form_class = MoviesCreateForm   
    template_name = 'actor_create.html'
    success_url = 'success'    
    
def success(request):
    return HttpResponse("Added record")

templates/actor_create.html
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create" />
</form>

templates/actor_list.html
<h1>Actors</h1>

<ul>
  {% for actor in object_list %}
    <li class="actor"><b>Name:</b>{{ actor.name }}, <b>DOB:</b>{{actor.dob}}, <b>Awards: </b>{{ actor.awards }}, <b>Total Credits: </b>{{actor.total_credits}},
	<b>Roles: </b>
	{% for role in actor.role_set.all %} <!--- using .all solves the problem ---->
	{{role.character}}, 
	{% endfor %}
	</li>
  {% endfor %}
</ul>

templates/movie_l.html
<h1>Movies</h1>

<ul>
  {% for movie in object_list %}
    <li class="movie"><b>Title:</b>{{ movie.title }}, <b>Release Date:</b>{{movie.rel_date}}, <b>Genre: </b>{{ movie.genre }}, <b>Director: </b>{{movie.director.name}},
	<b>Actors: </b>
	{% for actor in movie.actor.all %} <!--- using .all solves the problem ---->
	{{actor.name}}, 
	{% endfor %}
	<b>IMDB Score:</b> {{movie.imdb_score}}
	</li>
  {% endfor %}
</ul>

templates/moviechar_list.html
<h1>{{movie}} Characters List</h1>
<ul>
  {% for role in queryset %}
    <li class="role">Character: {{role.character}}, Actor: {{role.actor.name}}
	</li>
  {% endfor %}
</ul>